### PR TITLE
fix datetime.time from xls to json format issue #99

### PR DESCRIPTION
**Pull request by telmojsneves**

### CODE REVIEW

**Comment by rgrp** [comment]
@telmojsneves why did you close? Is the fix bad?

**Comment by telmojsneves** [comment]
No I am just a git noob that doesnt have a lot of experience with github. I
will re open it.

**Comment by telmojsneves** [comment]
reopen it.

**Comment by telmojsneves** [comment]
Why did the build failed?

**Comment by rgrp** [comment]
@telmojsneves i think build failed due to lack of a dependency in the requirements file that we should add. do not worry for now.

**Comment by telmojsneves** [comment]
When that PyPi will be updated? the last release was upload 2 years ago.

Thanks

**Pull request merged**
